name: expedier
description: "Expedier Assessment Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  animated_snack_bar: ^0.4.0
  local_auth: ^2.3.0
  camera: ^0.11.1
  gif_view: ^1.0.2
  move_to_background: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/auth/
    - assets/extras/
    - assets/faces/
    - assets/nav/
    - assets/onboard/
